# Generated by Django 4.1 on 2023-12-14 11:57

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail_t', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=200)),
                ('description', django_quill.fields.QuillField()),
                ('slug', models.SlugField(blank=True, max_length=300)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('starts', models.DateField(blank=True, null=True)),
                ('ends', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('ratingType', models.CharField(choices=[(' ', ' '), ('FIDE Rated', 'FIDE Rated'), ('Chess SA Rated', 'Chess SA Rated'), ('Online Rated', 'Online Rated'), ('Not Rated', 'Not Rated')], default=' ', max_length=100)),
                ('timeControl', models.CharField(choices=[(' ', ' '), ('Bullet', 'Bullet'), ('Blitz', 'Blitz'), ('Rapid', 'Rapid'), ('Classical', 'Classical')], default=' ', max_length=100)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('featured_tournament', models.BooleanField(blank=True, default=False, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'verbose_name_plural': 'tournaments',
            },
        ),
    ]
