# Generated by Django 4.2 on 2023-05-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournaments',
            name='slug',
            field=models.SlugField(blank=True, max_length=300),
        ),
    ]
