# Generated by Django 4.1 on 2022-08-03 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='date_posted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
