# Generated by Django 4.2 on 2023-06-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tournaments_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
