# Generated by Django 4.1 on 2022-08-03 23:49

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_articles_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='body',
            field=django_quill.fields.QuillField(),
        ),
    ]
