# Generated by Django 4.1 on 2022-08-03 23:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_alter_articles_body'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='QuillPost',
        ),
    ]
