# Generated by Django 4.2.3 on 2023-07-27 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_about_profile_chessdotcom_and_more'),
        ('blog', '0004_alter_articles_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournaments',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tournaments',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddField(
            model_name='tournaments',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournaments',
            name='timeControl',
            field=models.CharField(choices=[(' ', ' '), ('Bullet', 'Bullet'), ('Blitz', 'Blitz'), ('Rapid', 'Rapid'), ('Classical', 'Classical')], default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='ends',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='ratingType',
            field=models.CharField(choices=[(' ', ' '), ('FIDE Rated', 'FIDE Rated'), ('Chess SA Rated', 'Chess SA Rated'), ('Online Rated', 'Online Rated'), ('Not Rated', 'Not Rated')], default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='starts',
            field=models.DateField(blank=True, null=True),
        ),
    ]
