# Generated by Django 4.1 on 2023-12-14 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_tournaments_location_tournaments_owner_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ratings',
        ),
        migrations.DeleteModel(
            name='RatingsWorld',
        ),
        migrations.DeleteModel(
            name='Tournaments',
        ),
    ]
