# Generated by Django 4.1 on 2022-08-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_ratings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name_plural': 'articles'},
        ),
        migrations.AlterModelOptions(
            name='ratings',
            options={'verbose_name_plural': 'ratings'},
        ),
        migrations.AddField(
            model_name='ratings',
            name='age',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratings',
            name='position',
            field=models.IntegerField(default=' '),
        ),
    ]
