# Generated by Django 4.1 on 2022-08-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_articles_options_alter_ratings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
