# Generated by Django 4.1 on 2022-08-06 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_ratings_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='position',
        ),
    ]
