# Generated by Django 4.1 on 2022-08-06 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_ratings_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='age',
        ),
    ]
