# Generated by Django 4.1 on 2022-08-06 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_ratings_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='age',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratings',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
