# Generated by Django 4.1 on 2022-08-06 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_ratings_age_ratings_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratings',
            old_name='region',
            new_name='last_updated',
        ),
    ]
