# Generated by Django 4.1 on 2022-08-06 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_rename_region_ratings_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='last_updated',
        ),
    ]
