# Generated by Django 4.1 on 2022-08-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_tournaments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournaments',
            options={'verbose_name_plural': 'tournaments'},
        ),
        migrations.AddField(
            model_name='tournaments',
            name='date_posted',
            field=models.DateField(auto_now=True),
        ),
    ]
