# Generated by Django 4.1 on 2022-08-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_ratingsworld'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingsworld',
            options={'verbose_name_plural': 'world_ratings'},
        ),
        migrations.AddField(
            model_name='articles',
            name='featured_article',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='tournaments',
            name='featured_tournament',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
