# Generated by Django 4.2 on 2023-04-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_ratingsworld_options_articles_featured_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
