# Generated by Django 4.2 on 2023-04-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_articles_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournaments',
            name='date_posted',
            field=models.DateField(auto_now_add=True),
        ),
    ]
