# Generated by Django 4.2 on 2023-04-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_tournaments_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournaments',
            name='ratingType',
            field=models.CharField(choices=[(' ', ' '), ('FIDE Rated', 'FIDE Rated'), ('Chess SA Rated', 'Chess SA Rated'), ('Not Rated', 'Not Rated')], default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='ends',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='starts',
            field=models.DateField(),
        ),
    ]
