# Generated by Django 4.2 on 2023-04-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_tournaments_ratingtype_alter_tournaments_ends_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='subtitle',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
